# Generated by Django 3.0.8 on 2020-07-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='listing',
            new_name='listingId',
        ),
        migrations.RenameModel(
            old_name='listings',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='listingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
