# Generated by Django 3.0.8 on 2020-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200721_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='currentPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='startingBid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
