# Generated by Django 3.0.8 on 2020-07-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200723_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='creator',
        ),
    ]
