# Generated by Django 3.0.8 on 2020-07-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchlist',
            new_name='watch',
        ),
    ]
