# Generated by Django 3.0.8 on 2020-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watch_bidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('d', 'disabled')], default='a', max_length=1),
        ),
    ]
